---
apiVersion: tf.tungsten.io/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: tf
spec:
  services:
    analytics:
      metadata:
        labels:
          tf_cluster: cluster1
        name: analytics1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: analyticsapi
            image: contrail-analytics-api
          - name: collector
            image: contrail-analytics-collector
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
    queryengine:
      metadata:
        labels:
          tf_cluster: cluster1
        name: queryengine1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: queryengine
            image: contrail-analytics-query-engine
    analyticsSnmp:
      metadata:
        labels:
          tf_cluster: cluster1
        name: analyticssnmp1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
          - name: analytics-snmp-collector
            image: contrail-analytics-snmp-collector
          - name: analytics-snmp-topology
            image: contrail-analytics-snmp-topology
    analyticsAlarm:
      metadata:
        labels:
          tf_cluster: cluster1
        name: analyticsalarm1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
          - name: analytics-alarm-gen
            image: contrail-analytics-alarm-gen
          - name: kafka
            image: contrail-external-kafka
    cassandras:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: configdb1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: cassandra
            image: contrail-external-cassandra
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
    rabbitmq:
      metadata:
        labels:
          tf_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: rabbitmq
            image: contrail-external-rabbitmq
    redis:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: redis1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: redis
            image: contrail-external-redis
          - name: stunnel
            image: contrail-external-stunnel
    webui:
      metadata:
        labels:
          tf_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          controlInstance: control1
          containers:
          - name: webuijob
            image: contrail-controller-webui-job
          - name: webuiweb
            image: contrail-controller-webui-web
    zookeeper:
      metadata:
        labels:
          tf_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            - name: zookeeper
              image: contrail-external-zookeeper
