---
apiVersion: tf.tungsten.io/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: tf
spec:
  commonConfiguration:
    hostNetwork: true
  services:
    analytics:
      metadata:
        labels:
          tf_cluster: cluster1
        name: analytics1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
          analyticsCassandraInstance: configdb1
          cassandraInstance: configdb1
          configInstance: config1
          redisInstance: redis1
          containers:
          - name: analyticsapi
            image: contrail-analytics-api
          - name: collector
            image: contrail-analytics-collector
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
    queryengine:
      metadata:
        labels:
          tf_cluster: cluster1
        name: queryengine1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          configInstance: config1
          analyticsInstance: analytics1
          zookeeperInstance: zookeeper1
          analyticsCassandraInstance: configdb1
          redisInstance: redis1
          containers:
          - name: queryengine
            image: contrail-analytics-query-engine
    analyticsSnmp:
      metadata:
        labels:
          tf_cluster: cluster1
        name: analyticssnmp1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
          cassandraInstance: configdb1
          configInstance: config1
          analyticsInstance: analytics1
          containers:
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
          - name: analytics-snmp-collector
            image: contrail-analytics-snmp-collector
          - name: analytics-snmp-topology
            image: contrail-analytics-snmp-topology
    analyticsAlarm:
      metadata:
        labels:
          tf_cluster: cluster1
        name: analyticsalarm1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
          cassandraInstance: configdb1
          configInstance: config1
          analyticsInstance: analytics1
          redisInstance: redis1
          containers:
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
          - name: analytics-alarm-gen
            image: contrail-analytics-alarm-gen
          - name: kafka
            image: contrail-external-kafka
    cassandras:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: configdb1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          configInstance: config1
          analyticsInstance: analytics1
          containers:
          - name: cassandra
            image: contrail-external-cassandra
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
    config:
      metadata:
        labels:
          tf_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
          cassandraInstance: configdb1
          analyticsInstance: analytics1
          containers:
          - name: api
            image: contrail-controller-config-api
          - name: devicemanager
            image: contrail-controller-config-devicemgr
          - name: dnsmasq
            image: contrail-controller-config-dnsmasq
          - name: schematransformer
            image: contrail-controller-config-schema
          - name: servicemonitor
            image: contrail-controller-config-svcmonitor
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
    controls:
    - metadata:
        labels:
          tf_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: configdb1
          configInstance: config1
          analyticsInstance: analytics1
          logLevel: SYS_DEBUG
          containers:
          - name: control
            image: contrail-controller-control-control
          - name: dns
            image: contrail-controller-control-dns
          - name: named
            image: contrail-controller-control-named
          - name: nodemanager
            image: contrail-nodemgr
          - name: provisioner
            image: contrail-provisioner
    kubemanagers:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: kubemanager1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
          cassandraInstance: configdb1
          configInstance: config1
          analyticsInstance: analytics1
          ipFabricForwarding: false
          ipFabricSnat: true
          hostNetworkService: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          containers:
          - name: kubemanager
            image: contrail-kubernetes-kube-manager
    rabbitmq:
      metadata:
        labels:
          tf_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          containers:
          - name: rabbitmq
            image: contrail-external-rabbitmq
    redis:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: redis1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          containers:
          - name: redis
            image: contrail-external-redis
          - name: stunnel
            image: contrail-external-stunnel
    vrouters:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: vrouter1
      spec:
        serviceConfiguration:
          logLevel: SYS_DEBUG
          controlInstance: control1
          statusImage: contrail-status
          containers:
          - name: nodeinit
            image: contrail-node-init
          - name: vrouterkernelinit
            image: contrail-vrouter-kernel-init
          - name: vrouterkernelbuildinit
            image: contrail-vrouter-kernel-build-init
          - name: provisioner
            image: contrail-provisioner
          - name: nodemanager
            image: contrail-nodemgr
          - name: vrouteragent
            image: contrail-vrouter-agent
          - name: vroutercni
            image: contrail-kubernetes-cni-init
    webui:
      metadata:
        labels:
          tf_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          configInstance: config1
          analyticsInstance: analytics1
          controlInstance: control1
          cassandraInstance: configdb1
          redisInstance: redis1
          logLevel: SYS_DEBUG
          containers:
          - name: webuijob
            image: contrail-controller-webui-job
          - name: webuiweb
            image: contrail-controller-webui-web
    zookeepers:
    - metadata:
        labels:
          tf_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          logLevel: SYS_DEBUG
          containers:
            - name: zookeeper
              image: contrail-external-zookeeper
